### ISSUE TITLE
[cep] validação de entrada de dados por pattern matching (regex dos Deuses

### ISSUE THREAD

**Issue by paodelonga** [paodelonga/incode-et02se04de01-estacionamento#1]
Meu peixe, o negócio é fazer o unbrickable papi 😜 segure essa, vuh!

A boa agora é: usar aquele reeegexzzz gostosinho dos deuses pra fazer esqueminha de pirâmide
(pattern matching) para validar CORRETAMENTE a inputs em interações e dar aquele feedback
maneirasso pro usuario que usufruir desta proeza de forma INCORRETA (de acordo os monges)

Agora pegue esta cacetinha por exemplo só pra ficar ligado:

https://github.com/paodelonga/incode-et02se04de01-estacionamento/blob/d215d4494a125e6c67331240b16437c9c79c5a87/src/maquina_de_ticket/Utilidade/LeituraUtilidade.java#L17-L25

---

> [Ainda tá de pé aquela proposta?
Você faz aquilo só pra mim
Eu faço o que você gosta](https://www.youtube.com/watch?v=7Tl4RGRUzxY)

**Comment by forge-26** [comment]
tá foda ein fião, bom de acertar isso já

**Comment by paodelonga** [comment]
> esse tipo de commit ainda vai quebrar minha reputação por aqui (inexistente
